### PR TITLE
Updated README.md to use EmberCLI semantics

### PR DESCRIPTION
**Pull request by taras**
- Renamed  to *Ember List*
- Changed examples to assume EmberCLI
- Changed installation to use EmberCLI
- Changed Handlebars examples to use {{ember-list}} helper

### CODE REVIEW

**Comment by ebryn** [comment]
Was there a conversation about renaming to "Ember List"?

**Comment by taras** [comment]
@stefanpenner and I started talking about releasing the addon and we agreed to publish it on NPM as `ember-list`. Also, I'm using `{{ember-list}}` helper in the examples since the *View* will become increasingly less relevant as approach Ember 2.0.

**Comment by ebryn** [comment]
I'm not really a fan of Ember List, it's too generic sounding. It also supports grids, so list doesn't feel totally right either.

**Comment by mmun** [comment]
Agree with @ebryn.

**Comment by taras** [comment]
@ebryn I'm with you. We need something other than *ListView* but I don't know what. Suggestions?

**Comment by ebryn** [comment]
I think we can punt on it a bit longer since it's still a View, and when we need to change it for 2.0 come up with a name potentially better than ListComponent :P

**Comment by taras** [comment]
Sure, what about npm package name?

**Comment by ebryn** [comment]
`ember-list-view` seems fine for now and we can always rename it later?

**Comment by taras** [comment]
Ok, but I still want to remove reference to `Ember.ListView` because that's misleading. Should I just call it `ListView` in the README?

**Comment by ebryn** [comment]
`ListView` seems good to me

**Comment by taras** [comment]
Ok, I renamed `Ember.ListView` to `ListView` and `Ember.VirtualListView` to `VirtualListView`.

**Comment by stefanpenner** [comment]
most of this looks great, 2 things:

1. `import ListView from 'list-view/list-view' is kinda crappy
2. should we bike-shed the name `ListView` now or later? I think `ember-list-view` or `list-view` is good, even if it it does a grid, or variable height grids. As it is common to want to display a list-in many ways.

**Comment by jonnii** [comment]
@stefanpenner what about ember-masonry (rim-shot).

**Comment by stefanpenner** [comment]
> @stefanpenner what about ember-masonry (rim-shot).

heh, maybe once/if we actually support more packing algorithms. Unfortunately writing them in way that supports memorization, that is incremental + bound data structure friendly in a performant way is tricky. But i hope it happens someday :)

**Comment by taras** [comment]
> `import ListView from 'list-view/list-view' is kinda crappy

Can we do `import ListView from 'list-view'`?

**Comment by stefanpenner** [comment]
> Can we do import ListView from 'ember-list-view'?

this would be lovely.

**Comment by jonnii** [comment]
@stefanpenner on a serious note, what about instead of `ember-list-view`, something like `ember-layouts` or something like that. I know the plan is to land the packing stuff at some point, and then the name `ember-list-view` will be just one of the things this does.

**Comment by taras** [comment]
@stefanpenner I don't know how to do that with EmberCLI. Can you give me a hint and I'll figure it out from there?

**Comment by stefanpenner** [comment]
actually its kinda crappy, @joliss had a good idea but we haven't implemented it yet. For now it actually uses the re-exporter. https://github.com/ember-cli/ember-cli/blob/e38e6d8a65b9977ad3f51bbf57336deb77f2fd56/lib/models/addon.js#L472

**Pull request merged**
