### PR TITLE
Wrap callback to ember run bind

### PR DESCRIPTION
**Pull request by AmilKey**

### CODE REVIEW

**Comment by stefanpenner** [comment]
nope, this one isn't supposed to be wrapped in a bind.

**Comment by AmilKey** [comment]
@stefanpenner what are scroll events should trigger ember mutations?

**Comment by stefanpenner** [comment]
> @stefanpenner what are scroll events should trigger ember mutations?

Basically, we only need to enter ember world, when a view is recycled. Although we may receive scroll events extremely often and quickly. We only need to update the scrolling slabs position each scroll event and recycle views on average only every 1/10 scroll events.

Desktop browsers wont notice but some of our slower mobile browsers will notice.

Beyond that we can mutate the DOM in faster way by doing it manually.  This is mainly to ensure performance of scrolling on mobile devices.

**Comment by AmilKey** [comment]
@stefanpenner ok, i understand you, think one may close pull request.

**Comment by stefanpenner** [comment]
> @stefanpenner ok, i understand you, think one may close pull request.

Sometime in the future i hope to restore this functionality.  Likely as devices get faster, and as ember gets faster :)

**Pull request closed without merging**
