### PR TITLE
Upgraded to Ember 1.11.0

### PR DESCRIPTION
**Pull request by taras**
Re: #209

### CODE REVIEW

**Comment by tim-evans** [comment]
:heart:

**Comment by alexdiliberto** [comment]
:+1: Awesome!

**Comment by jasonmit** [comment]
:+1:

**Comment by stefanpenner** [comment]
@taras it was fun pairing on this stuff!

**Comment by taras** [comment]
@stefanpenner I spent all night yesterday trying to figure out why the remaining tests are failing and I didn't even make scratch. We might need to do it again if we want to get it out of the door in the near future.

**Comment by stefanpenner** [comment]
Yes. I am unfortunately spoken for until sunday. I may be able to sneak in some time before then. But does sometime Sunday work for you?

**Comment by taras** [comment]
Yep, let me know on Slack when you want to start. 

I did some investigating of the controller issue that we were debugging and it looks like it works correctly when I rebuild the example in dummy app and it work correctly. Either the helper is unreliable or something more sinister is going on :speak_no_evil:

**Comment by stefanpenner** [comment]
sinister sounds like fun to me

**Comment by taras** [comment]
I tested this branch against Ember master that includes [#10795](https://github.com/emberjs/ember.js/pull/10795) and all tests are passing. We're very close to being able to cut our first major releases with EmberCLI compatibility and Ember 1.10 & Ember 1.11.1 compatibility.

**Comment by slindberg** [comment]
Thanks @taras! :beers:

**Comment by alexdiliberto** [comment]
@taras :metal: :beer:

**Comment by pedrokiefer** [comment]
@taras :+1: :beer:

**Comment by mrinterweb** [comment]
@taras this is fantastic. I believe these issues were blocking my 1.11 upgrade. Thank you :beers: :cocktail:

**Comment by jasonmit** [comment]
@taras great job in moving this forward :+1:

**Pull request merged**
