### PR TITLE
Rebased Pack

### PR DESCRIPTION
**Pull request by taras**
This PR is #173 rebased against master. 
### TODO
- ~~[ ] EmptyListView implementation was removed~~ can be replaced with `{{#if isEmpty}} show empty {{else}}{{view 'list-view'}}{{/if}}`
- [ ] [http://localhost:4200/tests?testId=b2bd5b5c](http://localhost:4200/tests?testId=b2bd5b5c) fails due to fewer renders - maybe good/right, don't know.
- [ ] ...

### CODE REVIEW

**Comment by taras** [comment]
Rebased this branch against master after NPM release. Got some tests to fix.

**Comment by taras** [comment]
@stefanpenner @krisselden a87bdac3e28a80bab27668ec8325c4c5a1bea6b8 includes Kris' changes to pack. I'll create a list of fixes that need to be made.

**Comment by krisselden** [comment]
@taras what is the status here?

**Comment by taras** [comment]
I haven't allocated the time to work on this because Stef was busy and I don't know enough about `list-view` internals to know what tests fail because they're broken vs expected. If you have some cycles to work on this with me, then we should be able to make progress pretty quickly.

**Comment by krisselden** [comment]
@taras I'll try to help you shortly, I have to do some more refactoring beyond this too, to get to an API that feels right for Ember 2.0.  I've got a plan, it will affect a few APIs, like the item view stuff, it will be more about layout and yielding, no more item view class stuff.

**Comment by krisselden** [comment]
you'll be able to refactor item view stuff using the component helper within the block.

**Comment by taras** [comment]
That's great. I'll take direction from you about the changes that need to be done. Let me know when you're ready to spend some time on this and I'll be available. Look forward to working on this :)

**Comment by jrhe** [comment]
Just set up my app with this branch and its working well. One bug though is that it no longer seems to add position:absolute to the list view items meaning that all the item transforms are wrong.

Additionally the layout-bin-packer dependency doesn't seem to be set up properly so I had to manually add it to vendor to get things working. Maybe related:
`[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-list-view]` when building.

What is left to do on this branch? If theres anything that I can do do/ test, let me know.

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...

**Pull request closed without merging**
