### PR TITLE
EmberCLI Compatibility: Addon & AMD

### PR DESCRIPTION
**Pull request by taras**
- Added ember-cli addon index.js file
- Brocfile now generates amd build
- AMD build being added to verdor dir

### CODE REVIEW

**Comment by stefanpenner** [comment]
good incremental step :+1:

**Comment by taras** [comment]
@stefanpenner yeah, definitely, just gotta find the time :)

**Comment by stefanpenner** [comment]
@taras awesome, thanks dude.

**Comment by jasonmit** [comment]
:+1:

**Comment by taras** [comment]
Well, this was awesome!

**Comment by fivetanley** [comment]
awesome!

**Pull request merged**
