### PR TITLE
Update to docs site

### PR DESCRIPTION
**Pull request by samselikoff**
- Jekyll site
- Partially done
- See here: http://www.samselikoff.com/list-view

Having trouble finishing this on my own, just bc I'm not super knowledgable about list-view. But, I did my best to take the latest info from readme and combine with the current website. 

It's also organized and hopefully easier to change. I figured I'd open a PR so I can get specific comments, or, we could just push it out + hopefully get some help on filling in the blanks.

### CODE REVIEW

**Comment by samselikoff** [comment]
#153 for reference

**Comment by samselikoff** [comment]
Some info I need to fill in the blanks:

1. Why do we use the `collection` helper?
2. Which params are required - `content`, `height` and `rowHeight`?
3. Why a view rather than a component?
4. When to use List vs VirtualList? CSS media query to guess when on mobile device? Which mobile OSs?
5. Is there a build anywhere I can link JSBins to? I see the "latest" link but I believe the examples are using .05. Which version should I use?

**Comment by SebastianSzturo** [comment]
Thanks for the ember-cli documentation. Hope this gets merged soon!

**Comment by stefanpenner** [comment]
amazing!

**Comment by stefanpenner** [comment]
> Why do we use the collection helper?

legacy... :P

**Comment by stefanpenner** [comment]
> Why a view rather than a component?

legacy

**Comment by stefanpenner** [comment]
> When to use List vs VirtualList? CSS media query to guess when on mobile device? Which mobile OSs?

touch enabled devices, various mobiles browsers don't report scroll during the momentum phase, but we should likely make a table of cases.

**Comment by stefanpenner** [comment]
> Is there a build anywhere I can link JSBins to? I see the "latest" link but I believe the examples are using .05. Which version should I use?

there was once, i suspect the build is borked. We need to resurrect this effort.

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...

**Pull request closed without merging**
