### PR TITLE
Horizontal scrolling

### PR DESCRIPTION
**Pull request by lumenlunae**
I needed a way to scroll horizontally instead. I saw a previous pull request that had isHorizontal flags spread across the code, but I tried to work up something more abstract.

To implement horizontal scrolling we essentially mean variable width. Where the original list has a totalHeight property, I added a totalWidth. To trigger this though, we need to set our height to something static.

I have a boundHeight property that you'll need to set to a number that your height will be. This then lets the content flow horizontally.

Quick notes:
All existing APIs are the same, so scrollTo is still scrollTo(y) to keep it compatible. I just added a scrollToOffset(x,y)

And uh, haven't quite gotten around to tests for this. ;D But I'm at a point where it looks fine and I can work on it on my site, so I figured I'd get it out here first for you to see as well.

Thanks for all the work on list-view!

### CODE REVIEW

**Comment by fivetanley** [comment]
@stefanpenner did you have time to review this?

**Comment by stefanpenner** [comment]
unfortunately all this code changes dramatically in the soon to be merged [pack branch ](https://github.com/emberjs/list-view/pull/173/files)

Additionally without tests this is unlikely to be accepted.

When it comes to horizontal scroll, I like the approach were we are basically scrolling through an infinite grid. My skim indicates this is closer to that.

**Comment by tim-evans** [comment]
(This is blocked by #173)

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...

**Pull request closed without merging**
